### ISSUE TITLE
singlepage->emergency

### ISSUE THREAD

**Issue by alex2** [isotoma/isotoma.recipe.apache#1]
At the moment, creating an emergency apache configuration using this recipe goes as follows:

``` ini
[buildout]
parts = apache-emergency

[apache-emergency]
recipe = isotoma.recipe.apache:singlepage
interfaces =
    *:80:www.example.com:false
    *:443:www.example.co.uk:true
htdocs = ${buildout:directory}/src/emergency
access_log = /var/ACCESSLOG 
error_log = /var/ERRORLOG
file_path = ${buildout:directory}/src/emergency/index.html
namevirtualhost = VIRTUALHOST
sslcert = ${buildout:directory}/cert.crt
sslkey = ${buildout:directory}/key.key
```

I do not like this. The interfaces _thing_ is horrible, ssl configuration is shared between all sites which makes the sitename-in-interfaces fairly useless, and I feel most importantly, it's more difficult to get values from my already-defined non-emergency parts.

I propose that instead of the above, we just do one emergency page per site per stanza, as follows:

``` ini
[buildout]
parts =
    apache
    apache-emergency

[apache]
recipe = isotoma.recipe.apache:wsgi
interface = 127.0.0.1
namevirtualhost = on
ssl = on
sslcert = /foo/bar/baz.crt
sslkey = /foo/bar/baz.key
<snip>

[apache-emergency]
<=apache
recipe = isotoma.recipe.apache:emergency
emergency-root = /var/www
emergency-page = index.html
```

This way, with very minimal duplication, we have a clearer configuration, potentially less duplication, and more control over what gets an emergency page and where.

The new method could be called _emergency_, rather than _singlepage_ to avoid confusion.

Le thoughts?

**Comment by Jc2k** [comment]
I don't think what you are describing is an emergency page. It's a planned downtime holding page. An emergency page is one that a site serves automatically in times of crisis, like 500 pages.

We have a different plan for emergency pages in zone land which won't require a separate vhost. It is probably applicable to Django, too. But mostly its for setups where pound has rather cheekily been throwing up unthemed timeout pages.

I think you are otherwise right though, if i'm parsing this correctly. The TL;DR is that isotoma.recipe.apache:static takes almost identical arguments to the :wsgi and :plone flavours of the recipe, then when we want a static version of a vhost we extend, change the recipe variant and point it at our static content.

Sounds lovely.

Can i ask that when install() fires, it copies the static content into /parts/PARTNAME/www rather than point into the checkout (not sure if that happens currently). For bonus points, I have a use for this recipe if i can pass parameters into an index.html.j2 template.

**Comment by alex2** [comment]
> I don't think what you are describing is an emergency page. It's a planned downtime holding page. An emergency page is one that a site serves automatically in times of crisis, like 500 pages.

I believe in non-plone land, we really just need a planned downtime page during maintenance (that serves all 503s, see https://gist.github.com/1507002).

> We have a different plan for emergency pages in zone land which won't require a separate vhost. It is probably applicable to Django, too. But mostly its for setups where pound has rather cheekily been throwing up unthemed timeout pages.

To provide a true "emergency" page for WSGI services, I guess we should aim to configure a 500/503 ErrorDocument as part of the WSGI recipe to act in a similar way to pound when the service is unavailable, but apache is alive.

> I think you are otherwise right though, if i'm parsing this correctly. The TL;DR is that isotoma.recipe.apache:static takes almost identical arguments to the :wsgi and :plone flavours of the recipe, then when we want a static version of a vhost we extend, change the recipe variant and point it at our static content.

Bingo, and all the typical vhost and ssl information gets reused.

> Can i ask that when install() fires, it copies the static content into /parts/PARTNAME/www rather than point into the checkout (not sure if that happens currently).

This would definitely be required and will be included.

> For bonus points, I have a use for this recipe if i can pass parameters into an index.html.j2 template.

I'm happy to include a template variable injection feature, and the copying of static content is definitely required.

Commits are a-comin...

**Comment by alex2** [comment]
The basics: 4eb7cd51e
Nicer file copyin': 1d2579f39
